### ISSUE TITLE
Develop a load testing tool

### ISSUE THREAD

**Issue by mikenikles** [mikenikles/your-analytics#206]
For local development and production load testing, we need a load testing tool to populate the ClickHouse database.

**Requirements**
- [x] Use https://oclif.io
- [x] Insert events through the `events-api`. Do not access ClickHouse directly!
- [x] Set default values for all options so that the tool can be run without specifying any options.
- [ ] Specify a date range for which to create events
    * E.g. April 5, 2020 to June 28, 2020
- [ ] Specify a min/max range combined with a time period
    * E.g. 10 - 25 events per hour; 2,000 - 3,500 events per day; etc.

**Tasks**
- [ ] Integrate `ya-load-testing` tests into the CI pipeline

**Usage**
`ya-load-testing`
* `--from`: Optional. Defaults to today - 3 months. Format YYYY-MM-DD.
* `--to`: Optional. Defaults to today. Format YYYY-MM-DD.
* `--min`: Optional. Defaults to 0. Number to indicate minimum number of events to record for a given `period`.
* `--max`: Optional. Defaults to 50. Number to indicate maximum number of events to record for a given `period`.
* `--period`: Optional. Defaults to `hour`. Possible values: `hour`, `day`, `month`

**Usage examples**
* `ya-load-testing`
* `ya-load-testing --from 2020-04-05 --to 2020-06-28 --min 10 --max 25 --period hour`
* `ya-load-testing --from 2002-01-01 --max 15000 --period month`

**Example - 30 days, 10 to 100 events per day**
* Flags
  * From: 2020-06-01
  * To: 2020-06-30
  * Min: 10
  * Max: 100
  * Period: Day
* Expected behavior
  * `buckets` = Difference in days from June 1 to 30 = 30 buckets
  * For each of the 30 `buckets`, create between 10 and 100 events with a random `timestamp` for the given day
  * Add each event to a queue as soon as it's generated
  * Have one/multiple subscriber(s) pull from the queue and use `sendEvent` in `./api.ts` to submit the event
