### ISSUE TITLE
Launch checklist

### ISSUE THREAD

**Issue by mikenikles** [mikenikles/your-analytics#217]
A couple of tasks before we open to the public:
- [x] Remove beta sign up on the landing page hero
- [x] Add a "Get Started" button next to the "Live Demo" button
- [x] Define pricing
- [ ] Apply the same color palette across the site (e.g. onboarding, auth, etc.)
    - See #227
